name: Terraform Provider CI
on:
  pull_request:
    paths-ignore:
      - "README.md"

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

env:
  CI: true
  COSMO_API_KEY: cosmo_669b576aaadc10ee1ae81d9193425705
  COSMO_API_URL: http://localhost:3001
  TERRAFORM_VERSION: 1.9.5
  COMSO_REF: main

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/checkout@v4.1.7
        with:
          repository: wundergraph/cosmo
          ref: ${{ env.COMSO_REF }}
          path: cosmo
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "cosmo/docker-compose.full.yml "
          up-flags: "--remove-orphans --detach"
          compose-flags: "--project-directory cosmo --profile default"
      - run: scripts/setup-fulldemo.sh
        working-directory: ./cosmo

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - uses: actions/setup-go@v5.0.2
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download

      - name: Run tests
        run: make testacc

      - name: Build
        run: make build

      - name: Install
        run: make install

      - name: Run e2e
        run: make e2e
